<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Akinator</title>
    <link rel="stylesheet" href="assets/styles/css/main.css">
</head>

<body>
    <header>
        <a href="index.php" class="homeBtn">Accueil</a>

        <nav>
            <?php if (isConnected()): ?>
                <a href="account.php">Mon compte</a>
                <a href="logout.php">Déconnexion</a>
            <?php else: ?>
                <a href="login.php">Connexion</a>
                <a href="register.php">Inscription</a>
            <?php endif; ?>

        </nav>

    </header>

    <main>
        <?php include_once $template; ?>
    </main>

    <footer> © 2024 3W Academy - All rights reserved</footer>
</body>

</html>