<form action="login.php" method="POST">
    <h1>Connexion</h1>

    <label for="email">Email</label>
    <input type="email" name="email" id="email" required>

    <label for="password">Mot de passe</label>
    <input type="password" name="password" id="password" required>

    <button type="submit">Se connecter</button>
    <?= isset($error) ? '<p style="color: red;">' . $error . '</p>' : '' ?>
</form>