<div class="register">
    <?php if (isset($error)): ?>
        <p style="color: red;"><?= $error ?></p>
    <?php endif; ?>

    <?php if (isset($success)): ?>
        <p style="color: green;"><?= $success ?></p>
    <?php endif; ?>

    <div class="glassmorphism-container">
        <h1>Bienvenue</h1>
        <p>Inscrivez-vous pour jouer</p>

        <div class="switch-container">
            <a class="switch-option register-btn-full switch-btn" href="register.php">
                Inscription
            </a>
            <a class="switch-option login-btn" href="login.php">
                Connexion
            </a>
        </div>
        <form action="register.php" method="POST">
            <label for="email">Email</label>
            <input class="glassmorphism-container" type="email" name="email" id="email" required>

            <label for="username">Nom d'utilisateur</label>
            <input class="glassmorphism-container" type="text" name="username" id="username" required>

            <label for="password">Mot de passe</label>
            <input class="glassmorphism-container" type="password" name="password" id="password" required>

            <button class="submit" type="submit">S'inscrire</button>
        </form>
    </div>
</div>